name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "share.lius.me"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "fd74a481158b4dbe9f45c5ec446b727b"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://share.lius.me"

# url to repo, displayed in the index page
REPO = "https://github.com/willow-god/pastebin-worker"

# url to the favicon
FAVICON = "https://sharzy.in/favicon-32x32.png"

# the name displayed in TOS
TOS_MAINTAINER = "LiuShen"

# the email displayed in TOS
TOS_MAIL = "01@liushen.fun"

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
